Am 335 Fully-validate connection parameters on save
atlanhq/atlan-python pull request #130
Opened 2023-09-27 13:53 UTC by ErnestoLoma

2023-09-27 14:25 UTC, cmgrote requested changes
One other general question — are we now validating responses as well as requests? I don't think we should validate the former, or we may end up not giving back whatever the server tells us and instead giving the user an error (which I don't think is desirable).

Even if an assigned user or admin has been removed, or previously set to some inaccurate value by some direct API call, we should still return the object to a user. We can validate it if they submit those details to change the object — but fundamentally we should only validate this information when sent in a request, not received in a response.

2023-09-27 14:52 UTC, ErnestoLoma commented on pyatlan/cache/group_cache.py
> +                raise ValueError(
Yes it needs to be a ValueError

2023-09-27 14:53 UTC, ErnestoLoma commented on pyatlan/cache/role_cache.py
> +                raise ValueError(f"Provided role ID {role_id} was not found in Atlan.")
Yes

2023-09-27 15:06 UTC, ErnestoLoma commented
Validation happens whenever the the object is instantiated. There is is a method that allows an object to be constructed without any validation, but it's all or nothing. If we turn off validation when marshalling objects from JSON I think we run the risk of hiding errors in the code the might have been exposed if an error was raised when handling data that is actually valid.

2023-09-27 15:52 UTC, cmgrote commented
> Validation happens whenever the the object is instantiated. There is is a method that allows an object to be constructed without any validation, but it's all or nothing. If we turn off validation when marshalling objects from JSON I think we run the risk of hiding errors in the code the might have been exposed if an error was raised when handling data that is actually valid.

Yeah, I don't want to switch of validation entirely. I'm more thinking there are levels of validation:

- Is the JSON well-formed (always on)
- Is the minimal information in the JSON for us to parse it, e.g. sufficient info to tell us whether it's an asset vs some other object (always on)

Contrasted with:

- Is the information in the JSON *correct* (only for requests a user creates and wants to POST, not used for anything we GET back)

This is akin to the idea of an attribute being "required" or not — answering this question really depends on the context:

- Very few attributes are required in a response (for assets, only a `typeName` and `guid`)
- Other attributes are required for update requests (i.e. `qualifiedName` and `name`)
- Still more attributes are required for requests to create an asset (i.e. `qualifiedName`, `name`, and `qualifiedName` or `guid` (+ `typeName`) of the asset in which the asset-to-create will be contained)

^^ Just like there isn't a simple all-or-nothing "required" for attributes, I don't think we should have a simple all-or-nothing "validated" for payloads — we need to vary the validation based on the context (in particular request vs response).

If Pydantic can't handle the contextual validation, then we should only implement the minimal "always-on" validation via Pydantic, and move the contextual validation out into other methods (e.g. just before invoking `_call_api`, in the worst case).

2023-09-28 13:07 UTC, cmgrote approved these changes

2023-09-28 13:15 UTC, merged