FT-843: Implement GET operation that takes a list of attributes and relationships
atlanhq/atlan-python pull request #458
Opened 2024-12-30 07:49 UTC by vaibhavatlan

Breaking Change:
- Changed the default setting of `ignore_relationships = False` to `ignore_relationships = True`

Features: 
- Added `attribute` and `relationships_attributes` params in `AssetClient.get_by_qualified_name()` and  `AssetClient.get_by_guid() ` which uses `fluent search`  and not the default raw api call

2025-01-03 09:39 UTC, Aryamanz29 requested changes
Good progress!
Here are a few minor changes:

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +                .where(CompoundQuery.active_assets())
- Can you please verify whether the `GET_ENTITY_BY_UNIQUE_ATTRIBUTE` API endpoint returns only `ACTIVE` assets? If it does, then adding `.where(CompoundQuery.active_assets())` is correct. Otherwise, if it returns both `ACTIVE` and `DELETED` assets, we should avoid adding this as it would result in a different response.

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
I believe we can remove the redundant `if` conditions:  
```python
if attributes:
...

if relationships_attributes:
...
```

This is because we already have a check above:  
```python
if (attributes and len(attributes)) or (
        relationships_attributes and len(relationships_attributes)
    ):
    ...
```

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +                .where(CompoundQuery.active_assets())
- Can you please verify whether the `GET_ENTITY_BY_GUID ` API endpoint returns only `ACTIVE` assets? If it does, then adding `.where(CompoundQuery.active_assets())` is correct. Otherwise, if it returns both `ACTIVE` and `DELETED` assets, we should avoid adding this as it would result in a different response.

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
I believe we can remove the redundant `if` conditions:  
```python
if attributes:
...

if relationships_attributes:
...
```

This is because we already have a check above:  
```python
if (attributes and len(attributes)) or (
        relationships_attributes and len(relationships_attributes)
    ):
    ...
```

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +        relationships_attributes: Optional[List[str]] = None,
I think we should update the type to:  

```python
attributes: Optional[Union[List[str], List[AtlanField]]] = None
relationships_attributes: Optional[Union[List[str], List[AtlanField]]] = None
```

This change reflects that the parameters can accept either a string or a search field as input, for example:  

```python
"name"  
Asset.NAME
```

2025-01-03 09:39 UTC, Aryamanz29 commented on pyatlan/client/asset.py
> +        relationships_attributes: Optional[List[str]] = None,
I think we should update the type to:  

```python
attributes: Optional[Union[List[str], List[AtlanField]]] = None
relationships_attributes: Optional[Union[List[str], List[AtlanField]]] = None
```

This change reflects that the parameters can accept either a string or a search field as input, for example:  

```python
"name"  
Asset.NAME
```

2025-01-03 12:33 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                .where(CompoundQuery.active_assets())
No it doesn't. Will remove .where(CompoundQuery.active_assets()).

2025-01-03 12:34 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                .where(CompoundQuery.active_assets())
No it doesn't. Will remove .where(CompoundQuery.active_assets()).

2025-01-03 12:36 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
Removed

2025-01-03 12:36 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
Removed

2025-01-03 12:38 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +        relationships_attributes: Optional[List[str]] = None,
Got it. Changed

2025-01-05 17:24 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
@Aryamanz29 
Encountered an issue when removing the `if` conditions:  
```python
if attributes:
...

if relationships_attributes:
...
```

It raised a `NoneType` error when either `attributes` or `relationships_attributes` was empty. Resolved it using the following approach:  
```python
for attribute in attributes or []:  # type: ignore[union-attr]
...

for relation_attribute in relationships_attributes or []:  # type: ignore[union-attr]
...
```

2025-01-05 17:25 UTC, vaibhavatlan commented on pyatlan/client/asset.py
> +                    search = search.include_on_relations(relation_attribute)
Encountered an issue when removing the `if` conditions:  
```python
if attributes:
...

if relationships_attributes:
...
```

It raised a `NoneType` error when either `attributes` or `relationships_attributes` was empty. Resolved it using the following approach:  
```python
for attribute in attributes or []:  # type: ignore[union-attr]
...

for relation_attribute in relationships_attributes or []:  # type: ignore[union-attr]
...
```

2025-01-06 12:50 UTC, Aryamanz29 approved these changes
LGTM!

Make sure when writing integration tests to check real-world scenarios (which I later fixed in my latest commits) ✅ 

For example, in your previous integration tests, you only tested for `[attributes=["name", "qualified_name"]` which misses cases for 🧪 

- `related_attributes`
- `attributes` (using `AtlanField`)
- `related_attributes` (using `AtlanField`)

2025-01-06 13:07 UTC, merged